apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bigip1-mgmt
  namespace: f5-bigip-mmabis
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "bigip1-mgmt", 
    "type": "ovn-k8s-cni-overlay",
    "topology": "localnet",
    "netAttachDefName": "f5-bigip-mmabis/bigip1-mgmt",
    "vlanID": 3004,
    "ipam": {}
  }'

